package com.mashuq.sarf;

public enum HtmlIds {
    present1,
    present2m,
    present2f,
    presentD2,
    present3m,
    present3f,
    presentD3m,
    presentD3f,
    present4,
    present5m,
    present5f,
    present6m,
    present6f,

    past1,
    past2m,
    past2f,
    pastD2,
    past3m,
    past3f,
    pastD3m,
    pastD3f,
    past4,
    past5m,
    past5f,
    past6m,
    past6f,


    subjunctive1,
    subjunctive2m,
    subjunctive2f,
    subjunctiveD2,
    subjunctive3m,
    subjunctive3f,
    subjunctiveD3m,
    subjunctiveD3f,
    subjunctive4,
    subjunctive5m,
    subjunctive5f,
    subjunctive6m,
    subjunctive6f,

    jussive1,
    jussive2m,
    jussive2f,
    jussiveD2,
    jussive3m,
    jussive3f,
    jussiveD3m,
    jussiveD3f,
    jussive4,
    jussive5m,
    jussive5f,
    jussive6m,
    jussive6f,

    imperative2m,
    imperative2f,
    imperativeD2,
    imperative5m,
    imperative5f,


    passive_present1,
    passive_present2m,
    passive_present2f,
    passive_presentD2,
    passive_present3m,
    passive_present3f,
    passive_presentD3m,
    passive_presentD3f,
    passive_present4,
    passive_present5m,
    passive_present5f,
    passive_present6m,
    passive_present6f,

    passive_past1,
    passive_past2m,
    passive_past2f,
    passive_pastD2,
    passive_past3m,
    passive_past3f,
    passive_pastD3m,
    passive_pastD3f,
    passive_past4,
    passive_past5m,
    passive_past5f,
    passive_past6m,
    passive_past6f,

    passive_subjunctive1,
    passive_subjunctive2m,
    passive_subjunctive2f,
    passive_subjunctiveD2,
    passive_subjunctive3m,
    passive_subjunctive3f,
    passive_subjunctiveD3m,
    passive_subjunctiveD3f,
    passive_subjunctive4,
    passive_subjunctive5m,
    passive_subjunctive5f,
    passive_subjunctive6m,
    passive_subjunctive6f,

    passive_jussive1,
    passive_jussive2m,
    passive_jussive2f,
    passive_jussiveD2,
    passive_jussive3m,
    passive_jussive3f,
    passive_jussiveD3m,
    passive_jussiveD3f,
    passive_jussive4,
    passive_jussive5m,
    passive_jussive5f,
    passive_jussive6m,
    passive_jussive6f,


    active_participle,
    passive_participle,
    verbal_noun;
}
