CREATE DATABASE sarf CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `sarf`.`verb_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `verb` VARCHAR(256) NULL,
  `processed` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `verb_UNIQUE` (`verb` ASC) VISIBLE);


CREATE TABLE `sarf`.sarf (
    `id` INT NOT NULL AUTO_INCREMENT,
    active_jussive_firstperson_masculine_feminine_plural varchar(127),
    active_jussive_firstperson_masculine_feminine_singular varchar(127),
    active_jussive_secondperson_feminine_dual varchar(127),
    active_jussive_secondperson_feminine_plural varchar(127),
    active_jussive_secondperson_feminine_singular varchar(127),
    active_jussive_secondperson_masculine_dual varchar(127),
    active_jussive_secondperson_masculine_plural varchar(127),
    active_jussive_secondperson_masculine_singular varchar(127),
    active_jussive_thirdperson_feminine_dual varchar(127),
    active_jussive_thirdperson_feminine_plural varchar(127),
    active_jussive_thirdperson_feminine_singular varchar(127),
    active_jussive_thirdperson_masculine_dual varchar(127),
    active_jussive_thirdperson_masculine_plural varchar(127),
    active_jussive_thirdperson_masculine_singular varchar(127),
    active_participle varchar(127),
    active_past_firstperson_masculine_feminine_plural varchar(127),
    active_past_firstperson_masculine_feminine_singular varchar(127),
    active_past_secondperson_feminine_dual varchar(127),
    active_past_secondperson_feminine_plural varchar(127),
    active_past_secondperson_feminine_singular varchar(127),
    active_past_secondperson_masculine_dual varchar(127),
    active_past_secondperson_masculine_plural varchar(127),
    active_past_secondperson_masculine_singular varchar(127),
    active_past_thirdperson_feminine_dual varchar(127),
    active_past_thirdperson_feminine_plural varchar(127),
    active_past_thirdperson_feminine_singular varchar(127),
    active_past_thirdperson_masculine_dual varchar(127),
    active_past_thirdperson_masculine_plural varchar(127),
    active_past_thirdperson_masculine_singular varchar(127),
    active_present_firstperson_masculine_feminine_plural varchar(127),
    active_present_firstperson_masculine_feminine_singular varchar(127),
    active_present_secondperson_feminine_dual varchar(127),
    active_present_secondperson_feminine_plural varchar(127),
    active_present_secondperson_feminine_singular varchar(127),
    active_present_secondperson_masculine_dual varchar(127),
    active_present_secondperson_masculine_plural varchar(127),
    active_present_secondperson_masculine_singular varchar(127),
    active_present_thirdperson_feminine_dual varchar(127),
    active_present_thirdperson_feminine_plural varchar(127),
    active_present_thirdperson_feminine_singular varchar(127),
    active_present_thirdperson_masculine_dual varchar(127),
    active_present_thirdperson_masculine_plural varchar(127),
    active_present_thirdperson_masculine_singular varchar(127),
    active_subjunctive_firstperson_masculine_feminine_plural varchar(127),
    active_subjunctive_firstperson_masculine_feminine_singular varchar(127),
    active_subjunctive_secondperson_feminine_dual varchar(127),
    active_subjunctive_secondperson_feminine_plural varchar(127),
    active_subjunctive_secondperson_feminine_singular varchar(127),
    active_subjunctive_secondperson_masculine_dual varchar(127),
    active_subjunctive_secondperson_masculine_plural varchar(127),
    active_subjunctive_secondperson_masculine_singular varchar(127),
    active_subjunctive_thirdperson_feminine_dual varchar(127),
    active_subjunctive_thirdperson_feminine_plural varchar(127),
    active_subjunctive_thirdperson_feminine_singular varchar(127),
    active_subjunctive_thirdperson_masculine_dual varchar(127),
    active_subjunctive_thirdperson_masculine_plural varchar(127),
    active_subjunctive_thirdperson_masculine_singular varchar(127),
    imperative_secondperson_feminine_plural varchar(127),
    imperative_secondperson_feminine_singular varchar(127),
    imperative_secondperson_masculine_feminine_dual varchar(127),
    imperative_secondperson_masculine_plural varchar(127),
    imperative_secondperson_masculine_singular varchar(127),
    passive_jussive_firstperson_masculine_feminine_plural varchar(127),
    passive_jussive_firstperson_masculine_feminine_singular varchar(127),
    passive_jussive_secondperson_feminine_dual varchar(127),
    passive_jussive_secondperson_feminine_plural varchar(127),
    passive_jussive_secondperson_feminine_singular varchar(127),
    passive_jussive_secondperson_masculine_dual varchar(127),
    passive_jussive_secondperson_masculine_plural varchar(127),
    passive_jussive_secondperson_masculine_singular varchar(127),
    passive_jussive_thirdperson_feminine_dual varchar(127),
    passive_jussive_thirdperson_feminine_plural varchar(127),
    passive_jussive_thirdperson_feminine_singular varchar(127),
    passive_jussive_thirdperson_masculine_dual varchar(127),
    passive_jussive_thirdperson_masculine_plural varchar(127),
    passive_jussive_thirdperson_masculine_singular varchar(127),
    passive_participle varchar(127),
    passive_past_firstperson_masculine_feminine_plural varchar(127),
    passive_past_firstperson_masculine_feminine_singular varchar(127),
    passive_past_secondperson_feminine_dual varchar(127),
    passive_past_secondperson_feminine_plural varchar(127),
    passive_past_secondperson_feminine_singular varchar(127),
    passive_past_secondperson_masculine_dual varchar(127),
    passive_past_secondperson_masculine_plural varchar(127),
    passive_past_secondperson_masculine_singular varchar(127),
    passive_past_thirdperson_feminine_dual varchar(127),
    passive_past_thirdperson_feminine_plural varchar(127),
    passive_past_thirdperson_feminine_singular varchar(127),
    passive_past_thirdperson_masculine_dual varchar(127),
    passive_past_thirdperson_masculine_plural varchar(127),
    passive_past_thirdperson_masculine_singular varchar(127),
    passive_present_firstperson_masculine_feminine_plural varchar(127),
    passive_present_firstperson_masculine_feminine_singular varchar(127),
    passive_present_secondperson_feminine_dual varchar(127),
    passive_present_secondperson_feminine_plural varchar(127),
    passive_present_secondperson_feminine_singular varchar(127),
    passive_present_secondperson_masculine_dual varchar(127),
    passive_present_secondperson_masculine_plural varchar(127),
    passive_present_secondperson_masculine_singular varchar(127),
    passive_present_thirdperson_feminine_dual varchar(127),
    passive_present_thirdperson_feminine_plural varchar(127),
    passive_present_thirdperson_feminine_singular varchar(127),
    passive_present_thirdperson_masculine_dual varchar(127),
    passive_present_thirdperson_masculine_plural varchar(127),
    passive_present_thirdperson_masculine_singular varchar(127),
    passive_subjunctive_firstperson_masculine_feminine_plural varchar(127),
    passive_subjunctive_firstperson_masculine_feminine_singular varchar(127),
    passive_subjunctive_secondperson_feminine_dual varchar(127),
    passive_subjunctive_secondperson_feminine_plural varchar(127),
    passive_subjunctive_secondperson_feminine_singular varchar(127),
    passive_subjunctive_secondperson_masculine_dual varchar(127),
    passive_subjunctive_secondperson_masculine_plural varchar(127),
    passive_subjunctive_secondperson_masculine_singular varchar(127),
    passive_subjunctive_thirdperson_feminine_dual varchar(127),
    passive_subjunctive_thirdperson_feminine_plural varchar(127),
    passive_subjunctive_thirdperson_feminine_singular varchar(127),
    passive_subjunctive_thirdperson_masculine_dual varchar(127),
    passive_subjunctive_thirdperson_masculine_plural varchar(127),
    passive_subjunctive_thirdperson_masculine_singular varchar(127),
    verb varchar(127) NOT NULL,
    verbal_noun varchar(127),
    PRIMARY KEY (`id`),
    UNIQUE INDEX `verb_UNIQUE2` (`verb` ASC) VISIBLE
)